# Manipulando o campo logico e o de data

USE SUCOS;

ALTER TABLE tdcliente ADD PRIMARY KEY (CPF);

ALTER TABLE tdcliente ADD COLUMN (DATA_NASCIMENTO DATE);

INSERT INTO tdcliente (
CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, 
SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO) VALUES 
(
'00388934505', 'João da Silva', 'Rua projetada A número 10', '', 'VILA ROMAN',
'CARATINGA', 'AMAZONAS', '2222222', 32, 'M', 10000.00, 2000, 0, '1989-10-05'
);

SELECT * FROM tdcliente;