# Generated by Django 4.1.1 on 2022-09-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_animal_domestico_animal_nome_animal_animal_predador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='venoso',
            new_name='venenoso',
        ),
    ]
