# Generated by Django 4.1 on 2022-09-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_esgotado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_cadastro',
        ),
    ]
