# Generated by Django 4.1.1 on 2022-09-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlunoMoldel',
            new_name='AlunoModel',
        ),
        migrations.AlterModelOptions(
            name='alunomodel',
            options={'verbose_name': 'Aluno'},
        ),
        migrations.AlterModelOptions(
            name='cursomodel',
            options={'verbose_name': 'Curso'},
        ),
    ]
