# Generated by Django 4.1.1 on 2022-09-22 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_rename_alunomoldel_alunomodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], default='M', max_length=1)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.alunomodel')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.cursomodel')),
            ],
        ),
    ]
